title = "Burner Wallet Collective"
baseURL = "https://burnerwallet.co/"
languageCode = "en-us"
theme = "airspace-hugo"

# The site's parameters
[params]

  [menu]


    [[menu.header]]
      weight = 3
      name = "Host Event"
      url = "https://medium.com/gitcoin/how-to-host-a-burner-wallet-event-53a429035a24"
    [[menu.header]]
      weight = 4
      name = "Developers"
      url = "https://medium.com/gitcoin/burner-modules-c6737cf06fe"
    [[menu.header]]
      weight = 7
      name = "Launch Burner"
      url = "https://xdai.io"


    [[menu.footer]]
      weight = 1
      name = "View Code"
      url = "https://github.com/austintgriffith/burner-wallet"
    [[menu.footer]]
      weight = 2
      name = "Try Burner Wallet"
      url = "https://xdai.io/"
    [[menu.footer]]
      weight = 2
      name = "Emojicoin Exchange"
      url = "https://medium.com/gitcoin/emojicoin-exchange-53f9658c9e3b"
    [[menu.footer]]
      weight = 3
      name = "Paper Wallets"
      url = "https://github.com/austintgriffith/paper-wallet"
    [[menu.footer]]
      weight = 4
      name = "Support Collective"
      url = "https://gitcoin.co/grants/20/burner-wallet"
    [[menu.footer]]
      weight = 5
      name = "Learn More"
      url = "https://medium.com/@austin_48503"

  [params.slider]
    enable = true
    title = "Driving Onboarding and Adoption into Ethereum"
    subtitle = "The Burner Wallet is an instant web wallet used to send small amounts of crypto quickly with a simple UX"
    bgImage = "img/mainbg.jpg"
    btnText = "Support Burner Wallet Collective"
    url = "https://gitcoin.co/grants/20/burner-wallet"

  [params.wrapper]
    enable = true
    image = "img/burnerwallet.png"
    title = "Burner Wallet"
    italic = "The Burner wallet works in your mobile web browser so no app download and no seed phrase. It runs on the xDai network so transactions always completed within five seconds, you can do hundreds of them for a penny, and it’s pegged to the dollar so there is low cognitive overhead. The best part is onboarding is as easy as opening your camera."
    paragraph = "A burner wallet is automatically generated upon visiting xdai.io and your private key is stored in a local storage so it will be there when you come back. However, you should sweep any value you hold to a cold wallet regularly and burn your ephemeral private key. A burner wallet is analogous to cash; you won't carry too much because it can be lost but it's astonishingly easy to exchange. This can also be very handy in everyday use even for the crypto-initiated. If you are share a Lyft or a pizza with a friend and want to split the cost, just shoot their QR code with your camera and it will open up a new burner wallet to exchange value with them. Just don't forget to sweep to cold storage and burn your key when you get home!"
  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "Mission"
    bgImage = "img/featurebg.jpg"
    content = "In the short term, the Burner will drive onboarding by being irresistibly easy to use to move small amounts of crypto within the ecosystem and at events. In the near term, the Burner will act as a platform for games and apps. In the long run, the Burner will drive mass adoption, be ubiquitous in the space, and act as a cash replacement."

  [params.call]
    enable = true
    bgImage = "img/call-to-action-bg.jpg"
    title = "Join the Burner Wallet Collective"
    paragraph = "Calling all developers, designers, and UX studiers! The collective is an open initiative focused on pushing the burner mission forward."
    [params.call.button]
      url = "https://t.me/joinchat/KByvmROSyXhuMESDUL5YVA"
      text = "Join us on Telegram"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
